# Generated by Django 4.2.17 on 2024-12-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekSchoolApp', '0002_rename_event_locations_event_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_in_future',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_user',
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.CharField(default='25/12/2024 18:00-20:00', max_length=500),
        ),
    ]
